plugins {
    `java-library`
    `maven-publish`
    idea
    `jvm-test-suite`
    id("fabric-loom") version "1.10-SNAPSHOT"
}

version = property("mod_version") as String
group = property("mod_group_id") as String

// Same charset fix as the NeoForge template (build.gradle.kts) - see that file for the full explanation.
tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.compilerArgs.add("-Xmaxerrs")
    options.compilerArgs.add("10000")
}

repositories {
    mavenLocal()
    // Modrinth's Maven - lets Camerapture be declared as a normal Gradle dependency instead of a
    // hand-copied jar in libs/ (unlike the NeoForge side's Camera mod dependency, which has no such
    // repository available and must be dropped into libs/ manually - see build.gradle.kts).
    exclusiveContent {
        forRepository { maven("https://api.modrinth.com/maven") { name = "Modrinth" } }
        filter { includeGroup("maven.modrinth") }
    }
}

base {
    archivesName = property("mod_id") as String
}

tasks.withType<AbstractArchiveTask>().configureEach {
    isPreserveFileTimestamps = true
    isReproducibleFileOrder = false
}

// Same Java-version boundary as the NeoForge side: 1.20.1 runs on Java 17, everything from 1.20.5 (and
// thus every later Fabric node we add) needs Java 21.
val minecraftVersionForToolchain = property("minecraft_version") as String
java.toolchain.languageVersion = JavaLanguageVersion.of(if (minecraftVersionForToolchain.startsWith("1.20")) 17 else 21)

val minecraftVersion = property("minecraft_version") as String
val fabricLoaderVersion = property("fabric_loader_version") as String
val fabricApiVersion = property("fabric_api_version") as String
val camerapturePinnedVersion = property("camerapture_version") as String

dependencies {
    minecraft("com.mojang:minecraft:$minecraftVersion")
    // Official Mojang mappings (not Yarn's obfuscated-then-remapped names) - this is what keeps the
    // shared src/main/java tree source-compatible between the NeoForge and Fabric nodes: NeoForge only
    // ever uses Mojmap, so matching it here means class/method/field names line up identically on both
    // loaders and the vast majority of loader-agnostic code needs zero renaming to compile under Loom.
    mappings(loom.officialMojangMappings())

    modImplementation("net.fabricmc:fabric-loader:$fabricLoaderVersion")
    modImplementation("net.fabricmc.fabric-api:fabric-api:$fabricApiVersion")

    // maven.modrinth:<slug>:<version> - see the Modrinth exclusiveContent repository above.
    modImplementation("maven.modrinth:camerapture:$camerapturePinnedVersion")

    // NeoForge pulls this in transitively; a plain Fabric Loom project doesn't, so every @Nullable
    // annotation across the shared src/main/java tree (there are many) needs it declared explicitly here.
    compileOnly("com.google.code.findbugs:jsr305:3.0.2")
}

// A plain literal, not a "run-$minecraftVersion-..." interpolation: Loom's RunConfigSettings.runDir setter
// doesn't evaluate a string template the same way a NeoForge gameDirectory assignment does - interpolating
// minecraftVersion here silently produced the literal path segment "provider(?)" (a Gradle Provider's
// unresolved toString(), not the real value) even though that same val works fine everywhere else in this
// file (see the "minecraft:$minecraftVersion" dependency coordinate above). Each node still gets its own
// isolated run directory via the subproject folder itself (versions/1.21.1-fabric/run/, versions/
// 1.20.1-fabric/run/, ...) since runDir is resolved relative to the subproject, not shared across nodes.
loom {
    runs {
        named("client") {
            client()
            programArgs("--username", "LordFinn")
            runDir = "run"
        }
        named("server") {
            server()
            runDir = "run-server"
        }
    }
}

testing {
    suites {
        named<JvmTestSuite>("test") {
            useJUnitJupiter("5.10.2")
            dependencies {
                implementation("org.mockito:mockito-core:5.11.0")
            }
        }
    }
}

// Include resources generated by data generators, same as the NeoForge side.
sourceSets.main {
    resources.srcDir(rootProject.file("src/generated/resources"))
}

// WALKING-SKELETON STAGE: the shared src/main/java tree is still overwhelmingly NeoForge-only code
// (DeferredRegister, IEventBus, @Mod/@SubscribeEvent scattered across individual files - not just a few
// hub files, confirmed by attempting to widen this include list: procedures/, utils/, network/, world/
// inventory/ and voicechat/ are a tangled mesh, not a clean layered dependency, so "port items first, then
// menus, then network" doesn't hold up as a compile-order strategy). This walking skeleton stays narrowed
// to fr.lordfinn.crazyphone.fabric (the entrypoint/registration glue) plus the few files confirmed
// loader-agnostic (Crazyphone's MODID/resource() helpers, ModItems, CrazyPhoneItem, RegistryEntry) so the
// Loom+Stonecutter wiring itself stays verified end-to-end (compiles, mod loads, boots - confirmed live via
// :1.21.1-fabric:runServer reaching "Done"). Widening further needs a genuine porting pass per area (see
// tasks #160-166), not just adding more source directories - each area has real NeoForge-specific and
// Camera-mod-specific code to rewrite against Fabric/Camerapture APIs first.
sourceSets.main {
    val includes = mutableListOf(
        "fr/lordfinn/crazyphone/fabric/**",
        "fr/lordfinn/crazyphone/Crazyphone.java",
        "fr/lordfinn/crazyphone/init/ModItems.java",
        "fr/lordfinn/crazyphone/init/ModSounds.java",
        "fr/lordfinn/crazyphone/item/CrazyPhoneItem.java",
        "fr/lordfinn/crazyphone/utils/RegistryEntry.java",
        "fr/lordfinn/crazyphone/Config.java",
        "fr/lordfinn/crazyphone/utils/NbtCompat.java",
        "fr/lordfinn/crazyphone/utils/PhoneTagAccess.java",
        "fr/lordfinn/crazyphone/utils/RegistryCompat.java",
        "fr/lordfinn/crazyphone/utils/GameProfileCompat.java",
        "fr/lordfinn/crazyphone/utils/Contact.java",
        "fr/lordfinn/crazyphone/client/gui/components/MessageData.java",
        // ConversationSavedData's get()/load()/save() are now loader-gated with real vanilla
        // SavedData/DimensionDataStorage signatures for Fabric (javap-verified against the Loom-remapped
        // vanilla jar - NeoForge's own SavedData.Factory has convenience overloads plain vanilla doesn't).
        "fr/lordfinn/crazyphone/data/ConversationSavedData.java"
    )
    // CustomPacketPayload (and everything built on it: NetworkAccess's send methods, every packet record,
    // FeatureFlag's isEnabledFor gating) doesn't exist before 1.20.5 at all - see NetworkAccess.java's own
    // doc comment. 1.20.1-fabric stays at the narrower walking-skeleton scope above until its own
    // dedicated pre-1.20.5 networking pass (task #161 follow-up).
    if (minecraftVersion != "1.20.1") {
        includes += listOf(
            "fr/lordfinn/crazyphone/utils/NetworkAccess.java",
            "fr/lordfinn/crazyphone/FeatureFlag.java",
            "fr/lordfinn/crazyphone/client/ClientFeatureFlagState.java",
            "fr/lordfinn/crazyphone/network/FeatureFlagSyncPacket.java"
        )
    }
    java.setIncludes(includes)
}

// fabric.mod.json is expanded from a template the same way neoforge.mods.toml is - see
// src/main/fabric-templates/fabric.mod.json and generateModMetadata below - a separate directory from
// src/main/templates/ (the NeoForge template), NOT a subfolder of it: that NeoForge-side generateModMetadata
// task processes the entire src/main/templates tree unconditionally, and blows up trying to expand this
// file's Fabric-only placeholder tokens (undefined properties on any NeoForge node/gradle.properties).
val modMetadataProperties = mapOf(
    "minecraft_version" to property("minecraft_version"),
    "mod_id" to property("mod_id"),
    "mod_name" to property("mod_name"),
    "mod_license" to property("mod_license"),
    "mod_version" to property("mod_version"),
    "mod_authors" to property("mod_authors"),
    "mod_description" to property("mod_description"),
    "fabric_loader_version_range" to property("fabric_loader_version_range")
)
val generateModMetadata = tasks.register<ProcessResources>("generateModMetadata") {
    inputs.properties(modMetadataProperties)
    expand(modMetadataProperties)
    from(rootProject.file("src/main/fabric-templates"))
    into("build/generated/sources/modMetadata")
}
sourceSets.main {
    resources.srcDir(generateModMetadata)
}

publishing {
    publications {
        register<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            url = uri(layout.projectDirectory.dir("repo"))
        }
    }
}

idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}
