// Separate build script for the 26.x Fabric nodes (26.1-fabric, 26.2-fabric) - Minecraft 26.x ships
// UNOBFUSCATED (confirmed: the official version manifest for 26.1/26.1.2 has no client_mappings/
// server_mappings download entries at all - Mojang stopped publishing them starting at this version line).
// Fabric Loom's remapping pipeline (the plain "fabric-loom" plugin id used by build.fabric.gradle.kts,
// which every OTHER Fabric node here still uses) has nothing to remap against and fails outright
// ("Failed to find official mojang mappings for 26.1.2"). Loom ships a SEPARATE plugin id,
// "net.fabricmc.fabric-loom", for this new unobfuscated mode - same underlying plugin jar/version line,
// different marker id - confirmed against Fabric's own updated fabric-example-mod (26.1 branch) and the
// Loom GitHub issue tracker (#1541, "Loom still asks mappings after upgrading from 1.21.11 to 26.1").
// No mappings(...) dependency at all under this id, and mod dependencies use plain implementation(...)
// instead of modImplementation(...) - there's no intermediary-to-named remapping step left to need it.
plugins {
    `java-library`
    `maven-publish`
    idea
    `jvm-test-suite`
    id("net.fabricmc.fabric-loom") version "1.17-SNAPSHOT"
    // See build.gradle.kts's own copy of this comment - same pattern. Neither 26.1-fabric nor
    // 26.2-fabric actually publishes yet (see the fabricReadyToPublish check near the end of this
    // file), but declared here too so enabling one is a one-line change once it's ready, not a
    // structural one.
    id("com.modrinth.minotaur") version "2.9.0" apply false
    id("net.darkhax.curseforgegradle") version "1.1.28" apply false
}

version = property("mod_version") as String
group = property("mod_group_id") as String

// Same charset fix as the NeoForge template (build.gradle.kts) - see that file for the full explanation.
tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.compilerArgs.add("-Xmaxerrs")
    options.compilerArgs.add("10000")
}

repositories {
    mavenLocal()
}

base {
    archivesName = property("mod_id") as String
}

tasks.withType<AbstractArchiveTask>().configureEach {
    isPreserveFileTimestamps = true
    isReproducibleFileOrder = false
}

// Every node this script serves is 26.x, which requires Java 25 - see build.gradle.kts's own version of
// this same check for the full boundary explanation across every other version.
java.toolchain.languageVersion = JavaLanguageVersion.of(25)

val minecraftVersion = property("minecraft_version") as String
val fabricLoaderVersion = property("fabric_loader_version") as String
val fabricApiVersion = property("fabric_api_version") as String
// Same boundary as the NeoForge side's own mixinCompatibilityLevel (build.gradle.kts) - duplicated locally
// since this script's modMetadataProperties map (fabric.mod.json/crazyphone.fabric.mixins.json expansion)
// is deliberately separate from the NeoForge template's own token map (see that map's own doc comment).
// Left at JAVA_21 (Mixin's own compatibility-level enum doesn't have a JAVA_25 entry as of this writing) -
// revisit if Mixin itself needs bumping for 26.x.
val mixinCompatibilityLevel = "JAVA_21"

dependencies {
    minecraft("com.mojang:minecraft:$minecraftVersion")

    implementation("net.fabricmc:fabric-loader:$fabricLoaderVersion")
    implementation("net.fabricmc.fabric-api:fabric-api:$fabricApiVersion")

    // NeoForge pulls this in transitively; a plain Fabric Loom project doesn't, so every @Nullable
    // annotation across the shared src/main/java tree (there are many) needs it declared explicitly here.
    compileOnly("com.google.code.findbugs:jsr305:3.0.2")
}

// See build.fabric.gradle.kts's own doc comment on why runDir is a plain literal, not an interpolation.
loom {
    runs {
        named("client") {
            client()
            programArgs("--username", "LordFinn")
            runDir = "run"
        }
        named("server") {
            server()
            runDir = "run-server"
        }
    }
}

testing {
    suites {
        named<JvmTestSuite>("test") {
            useJUnitJupiter("5.10.2")
            dependencies {
                implementation("org.mockito:mockito-core:5.11.0")
            }
        }
    }
}

// Include resources generated by data generators, same as the NeoForge side.
sourceSets.main {
    resources.srcDir(rootProject.file("src/generated/resources"))
}

// Same walking-skeleton scope as build.fabric.gradle.kts's own >=1.20.5 branch - see that file's own doc
// comment for the full explanation. Kept as one literal copy here rather than a shared function so this
// script's own scope can diverge over time without threading a shared list through two build scripts.
sourceSets.main {
    val includes = mutableListOf(
        "fr/lordfinn/crazyphone/fabric/**",
        "fr/lordfinn/crazyphone/Crazyphone.java",
        "fr/lordfinn/crazyphone/init/ModItems.java",
        "fr/lordfinn/crazyphone/init/ModSounds.java",
        "fr/lordfinn/crazyphone/init/ModTabs.java",
        "fr/lordfinn/crazyphone/utils/PhotoResolution.java",
        "fr/lordfinn/crazyphone/item/CrazyPhoneItem.java",
        "fr/lordfinn/crazyphone/utils/RegistryEntry.java",
        "fr/lordfinn/crazyphone/Config.java",
        "fr/lordfinn/crazyphone/ClientConfig.java",
        "fr/lordfinn/crazyphone/utils/NbtCompat.java",
        "fr/lordfinn/crazyphone/utils/PhoneTagAccess.java",
        "fr/lordfinn/crazyphone/utils/RegistryCompat.java",
        "fr/lordfinn/crazyphone/utils/GameProfileCompat.java",
        "fr/lordfinn/crazyphone/utils/Contact.java",
        "fr/lordfinn/crazyphone/client/gui/components/MessageData.java",
        "fr/lordfinn/crazyphone/data/ConversationSavedData.java",
        "fr/lordfinn/crazyphone/data/PhotoSavedData.java",
        "fr/lordfinn/crazyphone/utils/NetworkAccess.java",
        "fr/lordfinn/crazyphone/FeatureFlag.java",
        "fr/lordfinn/crazyphone/client/ClientFeatureFlagState.java",
        "fr/lordfinn/crazyphone/network/FeatureFlagSyncPacket.java",
        "fr/lordfinn/crazyphone/data/PhoneRegistrySavedData.java",
        "fr/lordfinn/crazyphone/network/PhoneRegistrySyncPacket.java",
        "fr/lordfinn/crazyphone/data/PlayerPhoneState.java",
        "fr/lordfinn/crazyphone/network/PlayerPhoneStateSyncPacket.java",
        "fr/lordfinn/crazyphone/data/PhoneAttachmentTypes.java",
        "fr/lordfinn/crazyphone/client/ClientCallState.java",
        "fr/lordfinn/crazyphone/client/CallRingtoneManager.java",
        "fr/lordfinn/crazyphone/client/CallRingtonePlayer.java",
        "fr/lordfinn/crazyphone/client/CallVibrationTiming.java",
        "fr/lordfinn/crazyphone/network/CrazyPhoneCallStateSyncPacket.java",
        "fr/lordfinn/crazyphone/network/ConversationCallActivitySyncPacket.java",
        "fr/lordfinn/crazyphone/network/CrazyPhoneGroupMembershipNotificationPacket.java",
        "fr/lordfinn/crazyphone/procedures/GetCrazyPhoneNumberProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneAddContactToPhoneProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneGetContactsProcedure.java",
        "fr/lordfinn/crazyphone/procedures/ResetCrazyPhoneNumberProcedure.java",
        "fr/lordfinn/crazyphone/procedures/IsPhoneInUseProcedure.java",
        "fr/lordfinn/crazyphone/utils/GuiCompat.java",
        "fr/lordfinn/crazyphone/client/gui/PhoneScreen.java",
        "fr/lordfinn/crazyphone/client/gui/CrazyPhoneDefaultScreenScreen.java",
        "fr/lordfinn/crazyphone/client/gui/CrazyPhoneContactsScreenScreen.java",
        "fr/lordfinn/crazyphone/client/gui/CrazyPhoneConversationScreen.java",
        "fr/lordfinn/crazyphone/client/EmojiShortcodes.java",
        "fr/lordfinn/crazyphone/client/gui/CrazyPhoneGroupSettingsScreenScreen.java",
        "fr/lordfinn/crazyphone/client/gui/CrazyPhonePasswordScreenScreen.java",
        "fr/lordfinn/crazyphone/client/gui/CrazyPhoneMayorsCandidatesListScreen.java",
        "fr/lordfinn/crazyphone/client/gui/CrazyPhoneSignInScreenScreen.java",
        "fr/lordfinn/crazyphone/client/gui/CrazyphoneHomeScreenScreen.java",
        "fr/lordfinn/crazyphone/client/gui/CrazyPhoneContactInfoScreenScreen.java",
        "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneContactsScreenMenu.java",
        "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneConversationMenu.java",
        "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneGroupSettingsScreenMenu.java",
        "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneCallingScreenMenu.java",
        "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneInCallScreenMenu.java",
        "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneIncomingCallScreenMenu.java",
        "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneMayorsCandidatesListMenu.java",
        "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneContactInfoScreenMenu.java",
        "fr/lordfinn/crazyphone/world/inventory/CrazyPhonePasswordScreenMenu.java",
        "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneSignInScreenMenu.java",
        "fr/lordfinn/crazyphone/world/inventory/CrazyphoneHomeScreenMenu.java",
        "fr/lordfinn/crazyphone/client/gui/components/MessageDisplayManager.java",
        "fr/lordfinn/crazyphone/client/gui/components/CallBustPreview.java",
        "fr/lordfinn/crazyphone/client/gui/components/WrappedTextWidget.java",
        "fr/lordfinn/crazyphone/client/gui/components/ScrollingText.java",
        "fr/lordfinn/crazyphone/client/gui/components/CrazyPhoneColors.java",
        "fr/lordfinn/crazyphone/client/gui/components/PasswordEditBox.java",
        "fr/lordfinn/crazyphone/client/gui/components/SmallTextEditBox.java",
        "fr/lordfinn/crazyphone/client/gui/components/MessageWidget.java",
        "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneDefaultScreenMenu.java",
        "fr/lordfinn/crazyphone/init/ModMenus.java",
        "fr/lordfinn/crazyphone/init/ModScreens.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneGetGroupsProcedure.java",
        "fr/lordfinn/crazyphone/utils/ScreenMenuUtils.java",
        "fr/lordfinn/crazyphone/network/CrazyPhoneNewMessageNotificationPacket.java",
        "fr/lordfinn/crazyphone/utils/CrazyPhoneHelper.java",
        "fr/lordfinn/crazyphone/procedures/GetCrazyPhoneNumberFromMainHandProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneGetInitialFormValidationMessageProcedure.java",
        "fr/lordfinn/crazyphone/procedures/ResetCrazyPhoneNumberFromMainHandProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneInitialFormValidationButtonClickProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneTrySignInProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneGoBackScreenProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneLockProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneRemoveContactFromPhoneProcedure.java",
        "fr/lordfinn/crazyphone/procedures/IsPhoneItemStackInUseProcedure.java",
        "fr/lordfinn/crazyphone/procedures/IsPhoneSetupProcedure.java",
        "fr/lordfinn/crazyphone/procedures/RegisterNewPhoneFromFormProcedure.java",
        "fr/lordfinn/crazyphone/procedures/IsPhoneOpenProcedure.java",
        "fr/lordfinn/crazyphone/procedures/LoadPhoneDataIntoItemstackProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneOpenPasswordScreenProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneOpenSignInScreenProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneOnUseProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneRightclickedProcedure.java",
        "fr/lordfinn/crazyphone/client/CursorEffects.java",
        "fr/lordfinn/crazyphone/client/FakePlayerPreview.java",
        "fr/lordfinn/crazyphone/client/MojangProfileLookup.java",
        "fr/lordfinn/crazyphone/client/ClientMessageDraft.java",
        "fr/lordfinn/crazyphone/client/ConversationClientCache.java",
        "fr/lordfinn/crazyphone/voicechat/VoicechatIntegration.java",
        "fr/lordfinn/crazyphone/voicechat/VoiceMessageRecorder.java",
        "fr/lordfinn/crazyphone/network/UpdateContactInfoMessage.java",
        "fr/lordfinn/crazyphone/network/CrazyPhoneDefaultScreenButtonMessage.java",
        "fr/lordfinn/crazyphone/network/CrazyphoneHomeScreenButtonMessage.java",
        "fr/lordfinn/crazyphone/network/CrazyPhoneContactsScreenButtonMessage.java",
        "fr/lordfinn/crazyphone/network/CrazyPhoneGroupSettingsButtonMessage.java",
        "fr/lordfinn/crazyphone/network/CrazyPhoneMayorsCandidatesButtonMessage.java",
        "fr/lordfinn/crazyphone/network/CrazyPhonePasswordScreenButtonMessage.java",
        "fr/lordfinn/crazyphone/network/CrazyPhoneSignInScreenButtonMessage.java",
        "fr/lordfinn/crazyphone/network/CrazyPhoneContactInfoScreenButtonMessage.java",
        "fr/lordfinn/crazyphone/network/CrazyPhoneConversationButtonMessage.java",
        "fr/lordfinn/crazyphone/network/ConversationRequestPacket.java",
        "fr/lordfinn/crazyphone/network/ConversationResponsePacket.java",
        "fr/lordfinn/crazyphone/network/CrazyPhoneCallActionMessage.java",
        "fr/lordfinn/crazyphone/network/VoiceMessageUploadPacket.java",
        "fr/lordfinn/crazyphone/network/VoiceMessageAudioRequestPacket.java",
        "fr/lordfinn/crazyphone/network/VoiceMessageStopPacket.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneAddNewMayorCandidateProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneDeletePhoneByNumberProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneGivePhoneToPlayerFromNumberProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneListAndPrintPhonesProcedure.java",
        "fr/lordfinn/crazyphone/utils/ChatEventCompat.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneRemoveMayorCandidateProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneToggleElectionProcedure.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneToggleMayorVotingProcedure.java",
        "fr/lordfinn/crazyphone/procedures/RemoveVoteByNumberProcedure.java",
        "fr/lordfinn/crazyphone/procedures/ShowMayorVotesProcedure.java",
        "fr/lordfinn/crazyphone/procedures/VoteForMayorProcedure.java",
        "fr/lordfinn/crazyphone/command/ModCommands.java",
        "fr/lordfinn/crazyphone/data/OrphanedCallCleanup.java",
        "fr/lordfinn/crazyphone/item/CrazyPhoneItemProperties.java",
        "fr/lordfinn/crazyphone/client/PhoneClickableCursorHandler.java",
        "fr/lordfinn/crazyphone/procedures/CrazyPhoneItemInInventoryTickProcedure.java",
        "fr/lordfinn/crazyphone/network/CrazyPhoneUploadPicturePacket.java",
        "fr/lordfinn/crazyphone/network/CrazyPhonePictureRequestPacket.java",
        "fr/lordfinn/crazyphone/network/CrazyPhonePictureResponsePacket.java",
        "fr/lordfinn/crazyphone/network/CrazyPhoneGivePhotoItemPacket.java",
        "fr/lordfinn/crazyphone/network/CrazyPhoneMyPhotosActionMessage.java",
        "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneMyPhotosScreenMenu.java",
        "fr/lordfinn/crazyphone/client/gui/CrazyPhoneMyPhotosScreenScreen.java",
        "fr/lordfinn/crazyphone/item/CrazyPhonePhotoItem.java",
        "fr/lordfinn/crazyphone/client/render/CrazyPhonePhotoItemRenderer.java",
        "fr/lordfinn/crazyphone/client/picture/FabricPictureCapture.java",
        "fr/lordfinn/crazyphone/client/picture/FabricPictureCache.java",
        "fr/lordfinn/crazyphone/client/CrazyPhoneCaptureMode.java",
        "fr/lordfinn/crazyphone/mixin/CrazyPhoneCaptureFovMixin.java",
        "fr/lordfinn/crazyphone/mixin/CrazyPhoneCaptureHandMixin.java",
        "fr/lordfinn/crazyphone/mixin/CrazyPhoneCaptureGuiMixin.java",
        "fr/lordfinn/crazyphone/mixin/CrazyPhoneCaptureScrollMixin.java",
        "fr/lordfinn/crazyphone/mixin/CrazyPhoneCapturePressMixin.java",
        "fr/lordfinn/crazyphone/mixin/CrazyPhoneCaptureEscapeMixin.java",
        "fr/lordfinn/crazyphone/client/CrazyPhonePresentPose.java",
        "fr/lordfinn/crazyphone/client/ICrazyPhonePresentingState.java",
        "fr/lordfinn/crazyphone/mixin/LivingEntityRenderStateMixin.java",
        "fr/lordfinn/crazyphone/mixin/AvatarPresentPoseMixin.java",
        "fr/lordfinn/crazyphone/mixin/PlayerPresentPoseMixin.java",
        "fr/lordfinn/crazyphone/client/CrazyPhonePresentDebug.java",
        "fr/lordfinn/crazyphone/client/CrazyPhonePresentDebugCommand.java",
        "fr/lordfinn/crazyphone/mixin/CrazyPhonePresentHandGripMixin.java",
        "fr/lordfinn/crazyphone/mixin/CrazyPhonePresentHandGripInvokerMixin.java",
        "fr/lordfinn/crazyphone/mixin/CrazyPhoneItemModelRegistrationMixin.java",
        "fr/lordfinn/crazyphone/mixin/CrazyPhoneConditionalItemModelPropertyMixin.java",
        "fr/lordfinn/crazyphone/client/gui/CrazyPhonePhotoViewerScreen.java",
        "fr/lordfinn/crazyphone/item/CrazyPhoneCaptureShortcut.java",
        "fr/lordfinn/crazyphone/utils/PhotoItemData.java",
        "fr/lordfinn/crazyphone/recipe/CrazyPhoneDuplicatePhotoRecipe.java",
        "fr/lordfinn/crazyphone/init/ModRecipes.java",
        "fr/lordfinn/crazyphone/enchantment/ModEnchantments.java",
        "fr/lordfinn/crazyphone/data/SoulboundStash.java",
        "fr/lordfinn/crazyphone/enchantment/SoulboundHandler.java"
    )
    java.setIncludes(includes)
}

// fabric.mod.json is expanded from a template the same way neoforge.mods.toml is - see
// src/main/fabric-templates/fabric.mod.json and generateModMetadata below - see build.fabric.gradle.kts's
// own doc comment for why this lives in a separate directory from the NeoForge template.
// Mirrors build.fabric.gradle.kts's own fabricClientMixins - see that file's own doc comment (this is plain
// JSON, not Stonecutter-processed, so the //? if conditionals used everywhere else don't apply here either).
// Every mixin file actually included in this build's own compile scope above, in the "client" bucket
// (server-side mixins would go in mixins.json's own "mixins" array instead - none needed yet on this loader).
val fabricClientMixins = listOf(
    "CrazyPhoneCaptureFovMixin",
    "CrazyPhoneCaptureHandMixin",
    "CrazyPhoneCaptureGuiMixin",
    "CrazyPhoneCaptureScrollMixin",
    "CrazyPhoneCapturePressMixin",
    "CrazyPhoneCaptureEscapeMixin",
    "LivingEntityRenderStateMixin",
    "AvatarPresentPoseMixin",
    "PlayerPresentPoseMixin",
    "CrazyPhonePresentHandGripMixin",
    "CrazyPhonePresentHandGripInvokerMixin",
    "CrazyPhoneItemModelRegistrationMixin",
    "CrazyPhoneConditionalItemModelPropertyMixin"
).joinToString(",\n    ") { "\"$it\"" }

val modMetadataProperties = mapOf(
    "minecraft_version" to property("minecraft_version"),
    "mod_id" to property("mod_id"),
    "mod_name" to property("mod_name"),
    "mod_license" to property("mod_license"),
    "mod_version" to property("mod_version"),
    "mod_authors" to property("mod_authors"),
    "mod_description" to property("mod_description"),
    "fabric_loader_version_range" to property("fabric_loader_version_range"),
    "mixin_compatibility_level" to mixinCompatibilityLevel,
    "crazyphone_fabric_client_mixins" to fabricClientMixins
)
val generateModMetadata = tasks.register<ProcessResources>("generateModMetadata") {
    inputs.properties(modMetadataProperties)
    expand(modMetadataProperties)
    from(rootProject.file("src/main/fabric-templates"))
    into("build/generated/sources/modMetadata")
}
sourceSets.main {
    resources.srcDir(generateModMetadata)
}

// Ports build.gradle.kts's own >=26 processResources patches (see that file's own doc comment for the full
// reasoning on each) - this build script has no shared tasks.named<ProcessResources>("processResources")
// block with the NeoForge side, so each patch needs its own copy here. All three fixed a real, live-confirmed
// bug: crazy_phone_photo.json's tracked "minecraft:model" content never reaches our custom
// ModelImpl/SpecialRendererImpl dispatch (baked as an empty classic model instead, invisible everywhere -
// the missing-texture checkerboard); the loot modifier index file no longer has meaning on >=26 (every file
// under loot_modifiers/ is scanned directly now); and the duplicate-photo recipe serializer isn't registered
// on >=1.21.10 at all yet (ModRecipes.java's own <1.21.10 guard), so its untouched recipe JSON fails to load
// with "Unknown registry key" once shipped unfiltered.
tasks.named<ProcessResources>("processResources") {
    doLast {
        val photoModelFile = destinationDir.resolve("assets/crazyphone/models/item/crazy_phone_photo.json")
        photoModelFile.writeText("""{"type": "crazyphone:photo_card_model"}""" + "\n")
        val photoItemFile = destinationDir.resolve("assets/crazyphone/items/crazy_phone_photo.json")
        photoItemFile.writeText("""{"model": {"type": "crazyphone:photo_card_model"}}""" + "\n")
        destinationDir.resolve("data/neoforge/loot_modifiers/global_loot_modifiers.json").delete()
        destinationDir.resolve("data/crazyphone/recipe/duplicate_photo.json").delete()
        destinationDir.resolve("data/crazyphone/recipes/duplicate_photo.json").delete()
    }
}

publishing {
    publications {
        register<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            url = uri(layout.projectDirectory.dir("repo"))
        }
    }
}

// --- Modrinth / CurseForge publishing -----------------------------------------------------------
// See build.gradle.kts's own copy of this comment for the full reasoning. Per-node, not a single
// shared flag for both nodes this script serves - 26.1-fabric now compiles and boots clean
// (confirmed live, including the dynamic icon states fix), but 26.2-fabric doesn't yet (see
// PORTING-26x.md) - publishing it would just fail the release. Flip to minecraftVersion-based once
// 26.2-fabric is actually ready too, following build.fabric.gradle.kts's own project.name pattern.
val fabric26ReadyToPublish = minecraftVersion == "26.1.2"
val fabric26ModrinthProjectId = findProperty("modrinth_project_id") as String? ?: "REPLACE_WITH_MODRINTH_PROJECT_ID"
val fabric26CurseforgeProjectId = findProperty("curseforge_project_id") as String? ?: "REPLACE_WITH_CURSEFORGE_PROJECT_ID"
val fabric26ReleaseChangelog = System.getenv("RELEASE_CHANGELOG") ?: "See the GitHub release notes for this version."
// See build.gradle.kts's own copy of this comment - CurseForge's API rejected a game-version-only
// submission on the first real release run, and addJavaVersion() is the documented companion method.
val fabric26CurseforgeJavaVersion = "Java ${java.toolchain.languageVersion.get()}"

if (fabric26ReadyToPublish && System.getenv("MODRINTH_TOKEN") != null) {
    apply(plugin = "com.modrinth.minotaur")
    configure<com.modrinth.minotaur.ModrinthExtension> {
        token.set(System.getenv("MODRINTH_TOKEN"))
        projectId.set(fabric26ModrinthProjectId)
        versionNumber.set("${property("mod_version")}+fabric-$minecraftVersion")
        versionName.set("${property("mod_version")} - Fabric $minecraftVersion")
        versionType.set("release")
        // "jar", not "remapJar" like build.fabric.gradle.kts's own working copy of this block - 26.x's
        // own Loom variant (net.fabricmc.fabric-loom, the unobfuscated-mode plugin id, see this file's
        // own top-of-file doc comment) has no remapping step at all here (nothing to remap TO, Mojang
        // stopped publishing mappings for this version line), so it never registers a remapJar task in
        // the first place - confirmed live ("Task with name 'remapJar' not found in project
        // ':26.1-fabric'") the first time this gate actually got flipped on and tested for real, rather
        // than assumed from the sibling script's own (genuinely obfuscated, genuinely remapped) pattern.
        uploadFile.set(tasks.named("jar"))
        gameVersions.add(minecraftVersion)
        loaders.add("fabric")
        changelog.set(fabric26ReleaseChangelog)
    }
}

if (fabric26ReadyToPublish && System.getenv("CURSEFORGE_TOKEN") != null) {
    apply(plugin = "net.darkhax.curseforgegradle")
    tasks.register<net.darkhax.curseforgegradle.TaskPublishCurseForge>("publishCurseForge") {
        apiToken = System.getenv("CURSEFORGE_TOKEN")
        val mainFile = upload(fabric26CurseforgeProjectId, tasks.named("jar"))
        mainFile.changelog = fabric26ReleaseChangelog
        mainFile.changelogType = "markdown"
        mainFile.releaseType = "release"
        mainFile.addGameVersion(minecraftVersion)
        mainFile.addModLoader("Fabric")
        mainFile.addJavaVersion(fabric26CurseforgeJavaVersion)
        // See build.gradle.kts's own copy of this comment - CurseForge's error code 1021 ("You must
        // select at least one version from the environment group of versions") was the actual missing
        // piece, confirmed across every node in the same release run.
        mainFile.addEnvironment("Client")
        mainFile.addEnvironment("Server")
    }
}

idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}
