plugins {
    `java-library`
    `maven-publish`
    idea
    `jvm-test-suite`
    id("fabric-loom") version "1.10-SNAPSHOT"
}

version = property("mod_version") as String
group = property("mod_group_id") as String

// Same charset fix as the NeoForge template (build.gradle.kts) - see that file for the full explanation.
tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.compilerArgs.add("-Xmaxerrs")
    options.compilerArgs.add("10000")
}

repositories {
    mavenLocal()
}

base {
    archivesName = property("mod_id") as String
}

tasks.withType<AbstractArchiveTask>().configureEach {
    isPreserveFileTimestamps = true
    isReproducibleFileOrder = false
}

// Same Java-version boundary as the NeoForge side: 1.20.1 runs on Java 17, 1.20.5 through the 1.21.x line
// needs Java 21, and 26.x needs Java 25 - see build.gradle.kts's own version of this same check.
val minecraftVersionForToolchain = property("minecraft_version") as String
java.toolchain.languageVersion = JavaLanguageVersion.of(when {
    minecraftVersionForToolchain.startsWith("1.20") -> 17
    minecraftVersionForToolchain.startsWith("26.") -> 25
    else -> 21
})

val minecraftVersion = property("minecraft_version") as String
val fabricLoaderVersion = property("fabric_loader_version") as String
val fabricApiVersion = property("fabric_api_version") as String
// Same boundary as the NeoForge side's own mixinCompatibilityLevel (build.gradle.kts) - duplicated locally
// since this script's modMetadataProperties map (fabric.mod.json/crazyphone.fabric.mixins.json expansion)
// is deliberately separate from the NeoForge template's own token map (see that map's own doc comment).
val mixinCompatibilityLevel = if (minecraftVersion.startsWith("1.20")) "JAVA_17" else "JAVA_21"

dependencies {
    minecraft("com.mojang:minecraft:$minecraftVersion")
    // Official Mojang mappings (not Yarn's obfuscated-then-remapped names) - this is what keeps the
    // shared src/main/java tree source-compatible between the NeoForge and Fabric nodes: NeoForge only
    // ever uses Mojmap, so matching it here means class/method/field names line up identically on both
    // loaders and the vast majority of loader-agnostic code needs zero renaming to compile under Loom.
    mappings(loom.officialMojangMappings())

    modImplementation("net.fabricmc:fabric-loader:$fabricLoaderVersion")
    modImplementation("net.fabricmc.fabric-api:fabric-api:$fabricApiVersion")

    // NeoForge pulls this in transitively; a plain Fabric Loom project doesn't, so every @Nullable
    // annotation across the shared src/main/java tree (there are many) needs it declared explicitly here.
    compileOnly("com.google.code.findbugs:jsr305:3.0.2")
}

// A plain literal, not a "run-$minecraftVersion-..." interpolation: Loom's RunConfigSettings.runDir setter
// doesn't evaluate a string template the same way a NeoForge gameDirectory assignment does - interpolating
// minecraftVersion here silently produced the literal path segment "provider(?)" (a Gradle Provider's
// unresolved toString(), not the real value) even though that same val works fine everywhere else in this
// file (see the "minecraft:$minecraftVersion" dependency coordinate above). Each node still gets its own
// isolated run directory via the subproject folder itself (versions/1.21.1-fabric/run/, versions/
// 1.20.1-fabric/run/, ...) since runDir is resolved relative to the subproject, not shared across nodes.
loom {
    runs {
        named("client") {
            client()
            programArgs("--username", "LordFinn")
            runDir = "run"
        }
        named("server") {
            server()
            runDir = "run-server"
        }
    }
}

testing {
    suites {
        named<JvmTestSuite>("test") {
            useJUnitJupiter("5.10.2")
            dependencies {
                implementation("org.mockito:mockito-core:5.11.0")
            }
        }
    }
}

// Include resources generated by data generators, same as the NeoForge side.
sourceSets.main {
    resources.srcDir(rootProject.file("src/generated/resources"))
}

// WALKING-SKELETON STAGE: the shared src/main/java tree is still overwhelmingly NeoForge-only code
// (DeferredRegister, IEventBus, @Mod/@SubscribeEvent scattered across individual files - not just a few
// hub files, confirmed by attempting to widen this include list: procedures/, utils/, network/, world/
// inventory/ and voicechat/ are a tangled mesh, not a clean layered dependency, so "port items first, then
// menus, then network" doesn't hold up as a compile-order strategy). This walking skeleton stays narrowed
// to fr.lordfinn.crazyphone.fabric (the entrypoint/registration glue) plus the few files confirmed
// loader-agnostic (Crazyphone's MODID/resource() helpers, ModItems, CrazyPhoneItem, RegistryEntry) so the
// Loom+Stonecutter wiring itself stays verified end-to-end (compiles, mod loads, boots - confirmed live via
// :1.21.1-fabric:runServer reaching "Done"). Widening further needs a genuine porting pass per area (see
// tasks #160-166), not just adding more source directories - each area has real NeoForge-specific and
// Camera-mod-specific code to rewrite against native Fabric vanilla APIs first (not Camerapture - see
// FabricPictureCapture.java's own doc comment on why that turned out to be a dead end).
sourceSets.main {
    val includes = mutableListOf(
        "fr/lordfinn/crazyphone/fabric/**",
        "fr/lordfinn/crazyphone/Crazyphone.java",
        "fr/lordfinn/crazyphone/init/ModItems.java",
        "fr/lordfinn/crazyphone/init/ModSounds.java",
        "fr/lordfinn/crazyphone/init/ModTabs.java",
        "fr/lordfinn/crazyphone/utils/PhotoResolution.java",
        "fr/lordfinn/crazyphone/item/CrazyPhoneItem.java",
        "fr/lordfinn/crazyphone/utils/RegistryEntry.java",
        "fr/lordfinn/crazyphone/Config.java",
        "fr/lordfinn/crazyphone/ClientConfig.java",
        "fr/lordfinn/crazyphone/utils/NbtCompat.java",
        "fr/lordfinn/crazyphone/utils/PhoneTagAccess.java",
        "fr/lordfinn/crazyphone/utils/RegistryCompat.java",
        "fr/lordfinn/crazyphone/utils/GameProfileCompat.java",
        "fr/lordfinn/crazyphone/utils/Contact.java",
        "fr/lordfinn/crazyphone/client/gui/components/MessageData.java",
        // ConversationSavedData's get()/load()/save() are now loader-gated with real vanilla
        // SavedData/DimensionDataStorage signatures for Fabric (javap-verified against the Loom-remapped
        // vanilla jar - NeoForge's own SavedData.Factory has convenience overloads plain vanilla doesn't).
        "fr/lordfinn/crazyphone/data/ConversationSavedData.java",
        "fr/lordfinn/crazyphone/data/PhotoSavedData.java"
    )
    // CustomPacketPayload (and everything built on it: NetworkAccess's send methods, every packet record,
    // FeatureFlag's isEnabledFor gating) doesn't exist before 1.20.5 at all - see NetworkAccess.java's own
    // doc comment. 1.20.1-fabric stays at the narrower walking-skeleton scope above until its own
    // dedicated pre-1.20.5 networking pass (task #161 follow-up).
    if (minecraftVersion != "1.20.1") {
        includes += listOf(
            "fr/lordfinn/crazyphone/utils/NetworkAccess.java",
            "fr/lordfinn/crazyphone/FeatureFlag.java",
            "fr/lordfinn/crazyphone/client/ClientFeatureFlagState.java",
            "fr/lordfinn/crazyphone/network/FeatureFlagSyncPacket.java",
            "fr/lordfinn/crazyphone/data/PhoneRegistrySavedData.java",
            "fr/lordfinn/crazyphone/network/PhoneRegistrySyncPacket.java",
            "fr/lordfinn/crazyphone/data/PlayerPhoneState.java",
            "fr/lordfinn/crazyphone/network/PlayerPhoneStateSyncPacket.java",
            "fr/lordfinn/crazyphone/data/PhoneAttachmentTypes.java",
            "fr/lordfinn/crazyphone/client/ClientCallState.java",
            "fr/lordfinn/crazyphone/client/CallRingtoneManager.java",
            "fr/lordfinn/crazyphone/client/CallRingtonePlayer.java",
            "fr/lordfinn/crazyphone/client/CallVibrationTiming.java",
            "fr/lordfinn/crazyphone/network/CrazyPhoneCallStateSyncPacket.java",
            "fr/lordfinn/crazyphone/network/ConversationCallActivitySyncPacket.java",
            "fr/lordfinn/crazyphone/network/CrazyPhoneGroupMembershipNotificationPacket.java",
            // Loader-agnostic by inspection (no NeoForge/Camera imports), but transitively depend on
            // PhoneRegistrySavedData so they share its >=1.20.5 scoping.
            "fr/lordfinn/crazyphone/procedures/GetCrazyPhoneNumberProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneAddContactToPhoneProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneGetContactsProcedure.java",
            "fr/lordfinn/crazyphone/procedures/ResetCrazyPhoneNumberProcedure.java",
            "fr/lordfinn/crazyphone/procedures/IsPhoneInUseProcedure.java",
            // Screens/menus GUI reuse pass (task #166) - Tier 1: no NeoForge/Camera coupling beyond the
            // dead <1.20.5 PacketDistributor import (never active since Fabric is scoped >=1.20.5 here) and
            // MessageWidget's image-rendering methods (gated, Fabric renders text/voice/call bubbles but not
            // images yet - see CrazyPhoneHelper.getMessageFromTag's own Fabric TODO for the same reason).
            "fr/lordfinn/crazyphone/utils/GuiCompat.java",
            "fr/lordfinn/crazyphone/client/gui/PhoneScreen.java",
            "fr/lordfinn/crazyphone/client/gui/CrazyPhoneDefaultScreenScreen.java",
            "fr/lordfinn/crazyphone/client/gui/CrazyPhoneContactsScreenScreen.java",
            "fr/lordfinn/crazyphone/client/gui/CrazyPhoneConversationScreen.java",
            "fr/lordfinn/crazyphone/client/gui/CrazyPhoneGroupSettingsScreenScreen.java",
            "fr/lordfinn/crazyphone/client/gui/CrazyPhonePasswordScreenScreen.java",
            "fr/lordfinn/crazyphone/client/gui/CrazyPhoneMayorsCandidatesListScreen.java",
            // Calling/InCall/IncomingCall screens excluded here (need CrazyPhoneCallActionMessage ->
            // voicechat.CallRegistry -> SvcCallBridge, not ported this pass) - their MENU classes stay in
            // scope below since nothing tries to open them on Fabric (see ModScreens.java's own note).
            "fr/lordfinn/crazyphone/client/gui/CrazyPhoneSignInScreenScreen.java",
            "fr/lordfinn/crazyphone/client/gui/CrazyphoneHomeScreenScreen.java",
            "fr/lordfinn/crazyphone/client/gui/CrazyPhoneContactInfoScreenScreen.java",
            "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneContactsScreenMenu.java",
            "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneConversationMenu.java",
            "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneGroupSettingsScreenMenu.java",
            "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneCallingScreenMenu.java",
            "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneInCallScreenMenu.java",
            "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneIncomingCallScreenMenu.java",
            "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneMayorsCandidatesListMenu.java",
            "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneContactInfoScreenMenu.java",
            "fr/lordfinn/crazyphone/world/inventory/CrazyPhonePasswordScreenMenu.java",
            "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneSignInScreenMenu.java",
            "fr/lordfinn/crazyphone/world/inventory/CrazyphoneHomeScreenMenu.java",
            "fr/lordfinn/crazyphone/client/gui/components/MessageDisplayManager.java",
            "fr/lordfinn/crazyphone/client/gui/components/CallBustPreview.java",
            "fr/lordfinn/crazyphone/client/gui/components/WrappedTextWidget.java",
            "fr/lordfinn/crazyphone/client/gui/components/ScrollingText.java",
            "fr/lordfinn/crazyphone/client/gui/components/CrazyPhoneColors.java",
            "fr/lordfinn/crazyphone/client/gui/components/PasswordEditBox.java",
            "fr/lordfinn/crazyphone/client/gui/components/SmallTextEditBox.java",
            "fr/lordfinn/crazyphone/client/gui/components/MessageWidget.java",
            "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneDefaultScreenMenu.java",
            "fr/lordfinn/crazyphone/init/ModMenus.java",
            "fr/lordfinn/crazyphone/init/ModScreens.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneGetGroupsProcedure.java",
            "fr/lordfinn/crazyphone/utils/ScreenMenuUtils.java",
            // CrazyPhoneNewMessageNotificationPacket needs CrazyPhoneConversationScreen (now in scope
            // above); CrazyPhoneHelper needs CrazyPhoneNewMessageNotificationPacket - the cycle only
            // resolves once all three are compiled together in the same pass.
            "fr/lordfinn/crazyphone/network/CrazyPhoneNewMessageNotificationPacket.java",
            "fr/lordfinn/crazyphone/utils/CrazyPhoneHelper.java",
            // Loader-agnostic by inspection - needed nearly everywhere a phone number has to be read off
            // the item in the player's hand (button messages, call packets, screens).
            "fr/lordfinn/crazyphone/procedures/GetCrazyPhoneNumberFromMainHandProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneGetInitialFormValidationMessageProcedure.java",
            "fr/lordfinn/crazyphone/procedures/ResetCrazyPhoneNumberFromMainHandProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneInitialFormValidationButtonClickProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneTrySignInProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneGoBackScreenProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneLockProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneRemoveContactFromPhoneProcedure.java",
            "fr/lordfinn/crazyphone/procedures/IsPhoneItemStackInUseProcedure.java",
            "fr/lordfinn/crazyphone/procedures/IsPhoneSetupProcedure.java",
            "fr/lordfinn/crazyphone/procedures/RegisterNewPhoneFromFormProcedure.java",
            "fr/lordfinn/crazyphone/procedures/IsPhoneOpenProcedure.java",
            "fr/lordfinn/crazyphone/procedures/LoadPhoneDataIntoItemstackProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneOpenPasswordScreenProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneOpenSignInScreenProcedure.java",
            // CrazyPhoneOnUseProcedure - dispatches to the setup/lock/home flow. Its call-redirect
            // (CallRegistry) branch is gated neoforge-only with a Fabric fallback; the rest (including the
            // right-click dispatch below) is loader-agnostic now that Camera mod is gone.
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneOnUseProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneRightclickedProcedure.java",
            // CrazyPhoneConversationScreen needs these client-side helpers (all confirmed loader-agnostic).
            "fr/lordfinn/crazyphone/client/CursorEffects.java",
            "fr/lordfinn/crazyphone/client/FakePlayerPreview.java",
            "fr/lordfinn/crazyphone/client/MojangProfileLookup.java",
            "fr/lordfinn/crazyphone/client/ClientMessageDraft.java",
            "fr/lordfinn/crazyphone/client/ConversationClientCache.java",
            // isAvailable() is now dual-loader (FabricLoader.isModLoaded on Fabric) - everything else in
            // this package (CallRegistry, SvcCallBridge, ...) stays NeoForge-only for this pass, so on
            // Fabric this can report "available" while nothing actually wires up a call/voice packet yet.
            "fr/lordfinn/crazyphone/voicechat/VoicechatIntegration.java",
            // Fully loader-agnostic already - only the local mic-capture/OGG-encoding path, no networking.
            "fr/lordfinn/crazyphone/voicechat/VoiceMessageRecorder.java",
            // Remaining C2S button-message packets + voice/call packets (task #166 tail) - each gated
            // NeoForge-only where it touches CallRegistry/SvcCallBridge/Camera, matching CrazyPhoneHelper's
            // own partial-degradation pattern.
            "fr/lordfinn/crazyphone/network/UpdateContactInfoMessage.java",
            "fr/lordfinn/crazyphone/network/CrazyPhoneDefaultScreenButtonMessage.java",
            "fr/lordfinn/crazyphone/network/CrazyphoneHomeScreenButtonMessage.java",
            "fr/lordfinn/crazyphone/network/CrazyPhoneContactsScreenButtonMessage.java",
            "fr/lordfinn/crazyphone/network/CrazyPhoneGroupSettingsButtonMessage.java",
            "fr/lordfinn/crazyphone/network/CrazyPhoneMayorsCandidatesButtonMessage.java",
            "fr/lordfinn/crazyphone/network/CrazyPhonePasswordScreenButtonMessage.java",
            "fr/lordfinn/crazyphone/network/CrazyPhoneSignInScreenButtonMessage.java",
            "fr/lordfinn/crazyphone/network/CrazyPhoneContactInfoScreenButtonMessage.java",
            "fr/lordfinn/crazyphone/network/CrazyPhoneConversationButtonMessage.java",
            "fr/lordfinn/crazyphone/network/ConversationRequestPacket.java",
            "fr/lordfinn/crazyphone/network/ConversationResponsePacket.java",
            "fr/lordfinn/crazyphone/network/CrazyPhoneCallActionMessage.java",
            "fr/lordfinn/crazyphone/network/VoiceMessageUploadPacket.java",
            "fr/lordfinn/crazyphone/network/VoiceMessageAudioRequestPacket.java",
            "fr/lordfinn/crazyphone/network/VoiceMessageStopPacket.java",
            // Task #162 (event subscriptions): /crazyphone command tree. "candidate program" leaf excluded
            // on Fabric (Camera-mod dependent, see ModCommands.java's own note); everything else identical.
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneAddNewMayorCandidateProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneDeletePhoneByNumberProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneGivePhoneToPlayerFromNumberProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneListAndPrintPhonesProcedure.java",
            "fr/lordfinn/crazyphone/utils/ChatEventCompat.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneRemoveMayorCandidateProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneToggleElectionProcedure.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneToggleMayorVotingProcedure.java",
            "fr/lordfinn/crazyphone/procedures/RemoveVoteByNumberProcedure.java",
            "fr/lordfinn/crazyphone/procedures/ShowMayorVotesProcedure.java",
            "fr/lordfinn/crazyphone/procedures/VoteForMayorProcedure.java",
            "fr/lordfinn/crazyphone/command/ModCommands.java",
            "fr/lordfinn/crazyphone/data/OrphanedCallCleanup.java",
            "fr/lordfinn/crazyphone/item/CrazyPhoneItemProperties.java",
            "fr/lordfinn/crazyphone/client/PhoneClickableCursorHandler.java",
            "fr/lordfinn/crazyphone/procedures/CrazyPhoneItemInInventoryTickProcedure.java",
            // Native picture pipeline - real photo capture (with a full-screen zoom overlay)/storage/
            // full-size viewer, replacing the old Camera-mod/album-based feature entirely. NOT a Camerapture
            // integration (its own capture pipeline has no public "give me the bytes" hook, see
            // FabricPictureCapture's own doc comment). Being generalized to NeoForge incrementally (see the
            // implementation plan) - Fabric-only for now.
            "fr/lordfinn/crazyphone/network/CrazyPhoneUploadPicturePacket.java",
            "fr/lordfinn/crazyphone/network/CrazyPhonePictureRequestPacket.java",
            "fr/lordfinn/crazyphone/network/CrazyPhonePictureResponsePacket.java",
            "fr/lordfinn/crazyphone/network/CrazyPhoneGivePhotoItemPacket.java",
            "fr/lordfinn/crazyphone/network/CrazyPhoneMyPhotosActionMessage.java",
            "fr/lordfinn/crazyphone/world/inventory/CrazyPhoneMyPhotosScreenMenu.java",
            "fr/lordfinn/crazyphone/client/gui/CrazyPhoneMyPhotosScreenScreen.java",
            "fr/lordfinn/crazyphone/item/CrazyPhonePhotoItem.java",
            "fr/lordfinn/crazyphone/client/render/CrazyPhonePhotoItemRenderer.java",
            "fr/lordfinn/crazyphone/client/picture/FabricPictureCapture.java",
            "fr/lordfinn/crazyphone/client/picture/FabricPictureCache.java",
            // CrazyPhoneCaptureMode's core (enter/exit/tick/triggerCapture/drawOverlay) is loader-neutral;
            // the old Screen-based CrazyPhoneCaptureOverlayScreen/CrazyPhoneZoomController it replaced here
            // are gone entirely (that design couldn't keep the mouse grabbed while framing a shot - a real
            // Screen always releases it - so looking around while zoomed in was never possible on Fabric).
            // These five mixins are the Fabric-only equivalents of NeoForge's ViewportEvent.ComputeFov/
            // InputEvent.MouseScrollingEvent/InputEvent.MouseButton.Pre/RenderHandEvent/RenderGuiEvent.Post,
            // none of which Fabric API has a direct equivalent for. See crazyphone.fabric.mixins.json,
            // referenced only from fabric.mod.json.
            "fr/lordfinn/crazyphone/client/CrazyPhoneCaptureMode.java",
            "fr/lordfinn/crazyphone/mixin/CrazyPhoneCaptureFovMixin.java",
            "fr/lordfinn/crazyphone/mixin/CrazyPhoneCaptureHandMixin.java",
            "fr/lordfinn/crazyphone/mixin/CrazyPhoneCaptureGuiMixin.java",
            "fr/lordfinn/crazyphone/mixin/CrazyPhoneCaptureScrollMixin.java",
            "fr/lordfinn/crazyphone/mixin/CrazyPhoneCapturePressMixin.java",
            "fr/lordfinn/crazyphone/mixin/CrazyPhoneCaptureEscapeMixin.java",
            // Sneak-presenting a photo (arm pose + centered held-card render) - fully loader-neutral now:
            // CrazyPhonePresentPose and PlayerPresentPoseMixin have no NeoForge-specific parts left at all,
            // and the presenting-aware branches live directly in CrazyPhonePhotoItemRenderer (both first- and
            // third-person) instead of a separate render hook, so no Fabric-only mixin is needed for this
            // feature beyond the arm-pose one itself.
            "fr/lordfinn/crazyphone/client/CrazyPhonePresentPose.java",
            "fr/lordfinn/crazyphone/mixin/PlayerPresentPoseMixin.java",
            // Live-tunable knobs for the first-person presenting card, plus the /presentdebug client command
            // that edits them from chat - see CrazyPhonePresentDebug's own doc comment on why (avoiding
            // another recompile/relaunch round trip for every single 3D-offset guess).
            "fr/lordfinn/crazyphone/client/CrazyPhonePresentDebug.java",
            "fr/lordfinn/crazyphone/client/CrazyPhonePresentDebugCommand.java",
            // Redirects the OTHER (non-holding) hand's bare-arm base offset toward the card too, so both
            // hands visually appear to grip it instead of just the one actually holding the phone - see
            // that mixin's own doc comment.
            "fr/lordfinn/crazyphone/mixin/CrazyPhonePresentHandGripMixin.java",
            "fr/lordfinn/crazyphone/mixin/CrazyPhonePresentHandGripInvokerMixin.java",
            "fr/lordfinn/crazyphone/client/gui/CrazyPhonePhotoViewerScreen.java",
            // Punch-to-shoot - isHoldingPhone/clientOpenOverlay are loader-neutral, only the NeoForge event
            // handlers inside are gated; Fabric wires clientOpenOverlay via ClientPreAttackCallback instead
            // (see CrazyphoneFabricClient), which needs no separate empty-click handler of its own.
            "fr/lordfinn/crazyphone/item/CrazyPhoneCaptureShortcut.java",
            "fr/lordfinn/crazyphone/utils/PhotoItemData.java",
            // "Duplicate a photo with paper" crafting recipe - see CrazyPhoneDuplicatePhotoRecipe's own doc
            // comment (NeoForge-1.21.10 not backported yet; no equivalent Fabric node exists in this project).
            "fr/lordfinn/crazyphone/recipe/CrazyPhoneDuplicatePhotoRecipe.java",
            "fr/lordfinn/crazyphone/init/ModRecipes.java",
            // Task #164 (SavedData/player-attachment persistence): Soulbound enchantment death-drop
            // handling. ModEnchantments is loader-agnostic by inspection (only RegistryAccess/Registries.
            // ENCHANTMENT, no NeoForge imports); SoulboundStash now carries a Fabric Codec branch and
            // SoulboundHandler a full Fabric event-based implementation (ServerLivingEntityEvents.ALLOW_DEATH
            // + ServerPlayerEvents.AFTER_RESPAWN instead of LivingDropsEvent/PlayerEvent.Clone).
            "fr/lordfinn/crazyphone/enchantment/ModEnchantments.java",
            "fr/lordfinn/crazyphone/data/SoulboundStash.java",
            "fr/lordfinn/crazyphone/enchantment/SoulboundHandler.java"
        )
    }
    java.setIncludes(includes)
}

// fabric.mod.json is expanded from a template the same way neoforge.mods.toml is - see
// src/main/fabric-templates/fabric.mod.json and generateModMetadata below - a separate directory from
// src/main/templates/ (the NeoForge template), NOT a subfolder of it: that NeoForge-side generateModMetadata
// task processes the entire src/main/templates tree unconditionally, and blows up trying to expand this
// file's Fabric-only placeholder tokens (undefined properties on any NeoForge node/gradle.properties).
val modMetadataProperties = mapOf(
    "minecraft_version" to property("minecraft_version"),
    "mod_id" to property("mod_id"),
    "mod_name" to property("mod_name"),
    "mod_license" to property("mod_license"),
    "mod_version" to property("mod_version"),
    "mod_authors" to property("mod_authors"),
    "mod_description" to property("mod_description"),
    "fabric_loader_version_range" to property("fabric_loader_version_range"),
    "mixin_compatibility_level" to mixinCompatibilityLevel
)
val generateModMetadata = tasks.register<ProcessResources>("generateModMetadata") {
    inputs.properties(modMetadataProperties)
    expand(modMetadataProperties)
    from(rootProject.file("src/main/fabric-templates"))
    into("build/generated/sources/modMetadata")
}
sourceSets.main {
    resources.srcDir(generateModMetadata)
}

publishing {
    publications {
        register<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            url = uri(layout.projectDirectory.dir("repo"))
        }
    }
}

idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}
